{{- if .Values.frost.http.ingress.enabled -}}
{{- $tier := "http" -}}
{{- $fullName := include "frost-server.fullName" (merge (dict "tier" $tier) .) -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    {{ .Values.frost.http.ingress.rewriteAnnotation}}: {{ .Values.frost.http.ingress.rewriteTraget}}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
    component: {{ $tier }}
spec:
  rules:
  - host: {{ .Values.frost.http.serviceHost }}
    http:
      paths:
      - path:  {{ .Values.frost.http.ingress.path  }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ .Values.frost.http.ports.http.servicePort }}
{{- end -}}