{{- if and .Values.frost.http.ingress.enabled .Values.frost.mqtt.ingress.useSameAsHttp -}}
{{- $tier := "master" -}}
{{- $fullName := include "frost-server.fullName" (merge (dict "tier" $tier) .) -}}
{{- $defaultRewriteAnnotations := include "frost-server.ingress.rewriteAnnotation" (dict "scope" .Values.frost.http "type" $tier "fullName" $fullName "path" ( include "frost-server.http.serviceSubPath" . ) ) -}}
{{- /*BEGIN Predefine empty variables*/ -}}
{{- $annotations := dict -}}
{{- /*END Predefine empty variables*/ -}}
{{- if and .Values.frost.http.ingress.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.frost.http.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.frost.http.ingress.annotations "kubernetes.io/ingress.class" .Values.frost.http.ingress.ingressClassName}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  {{- $annotations = include "common.tplvalues.merge" ( dict "values" ( list .Values.frost.http.ingress.annotations $defaultRewriteAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    nginx.org/mergeable-ingress-type: "master"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
    component: {{ $tier }}
spec:
  {{- if and .Values.frost.http.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.frost.http.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.frost.http.ingress.tls.enabled }}
  tls:
    - hosts: 
        - {{ include "frost-server.http.serviceHost" . }}
      secretName: {{ .Values.frost.http.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ include "frost-server.http.serviceHost" . }}
{{- end -}}
