{{- if .Values.frost.mqtt.ingress.enabled -}}
{{- $tier := "mqtt" -}}
{{- $fullName := include "frost-server.fullName" (merge (dict "tier" $tier "merge" .Values.frost.mqtt.ingress.useSameAsHttp ) .) -}}
{{- $combine := false -}}
{{- if .Values.frost.mqtt.ingress.useSameAsHttp -}}
  {{- $combine = .Values.frost.http -}}
{{- end -}}
{{- $defaultRewriteAnnotations := include "frost-server.ingress.rewriteAnnotation" (dict "scope" .Values.frost.mqtt "type" $tier "fullName" $fullName "path" ( include "frost-server.mqtt.websockPath" . ) "combine"  $combine ) -}}
{{- if and .Values.frost.mqtt.ingress.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.frost.mqtt.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.frost.mqtt.ingress.annotations "kubernetes.io/ingress.class" .Values.frost.mqtt.ingress.ingressClassName}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.frost.mqtt.ingress.annotations $defaultRewriteAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- if .Values.frost.mqtt.ingress.useSameAsHttp }}
    nginx.org/mergeable-ingress-type: "minion"
  {{- end }}
  {{- /*Following annotation can't be described in the _helpers.tpl, so actually it has to stay here*/ -}}
  {{- if and (not .Values.frost.mqtt.ingress.useSameAsHttp) (or (eq .Values.frost.mqtt.ingress.ingressProvider "kubernetes-nginx") (not .Values.frost.mqtt.ingress.ingressProvider)) }}
    nginx.ingress.kubernetes.io/server-snippet: |
        location {{ template "frost-server.mqtt.websockPath" . }} {
          proxy_set_header Upgrade $http_upgrade;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header Connection "upgrade";
          proxy_cache_bypass $http_upgrade;
        }
  {{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
    component: {{ $tier }}
spec:
  {{- if and .Values.frost.mqtt.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.frost.mqtt.ingress.ingressClassName | default "nginx" }}
  {{- end }}
  {{- if and .Values.frost.mqtt.ingress.tls.enabled (not .Values.frost.mqtt.ingress.useSameAsHttp) }}
  tls:
    - hosts:
        - {{ include "frost-server.mqtt.serviceHost" . }}
      secretName: {{ .Values.frost.mqtt.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ include "frost-server.mqtt.serviceHost" . }}
    http:
      paths:
      - path:  {{ template "frost-server.mqtt.websockPath" . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name:  {{ $fullName }}
            port:
              number: {{ .Values.frost.mqtt.ports.websocket.servicePort }}
{{- end -}}
