apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frost-server.fullName" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
data:
  db.username: {{ .Values.frost.db.username }}
  db.password: {{ .Values.frost.db.password }}