version: 2
updates:
  # Maintain dependencies for Maven in the v2.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.openjfx:*"
        versions: ["[24,)"]
      - dependency-name: "org.liquibase:*"
  
  
  # Maintain dependencies for Maven in the v2.7.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.7.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "de.fraunhofer.iosb.io.moquette:*"
        versions: ["[0.18.3,)"]
      - dependency-name: "org.openjfx:*"
        versions: ["[24,)"]
      - dependency-name: "org.liquibase:*"
      - dependency-name: "de.grundid.opendatalab:geojson-jackson"
      - dependency-name: "de.fraunhofer.iosb.ilt:FROST-Client-Dynamic"
  
  
  # Maintain dependencies for Maven in the v2.6.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.6.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "de.fraunhofer.iosb.io.moquette:*"
        versions: ["[0.18.3,)"]
      - dependency-name: "org.openjfx:*"
        versions: ["[24,)"]
      - dependency-name: "org.liquibase:*"
      - dependency-name: "de.grundid.opendatalab:geojson-jackson"
      - dependency-name: "de.fraunhofer.iosb.ilt:FROST-Client-Dynamic"
  
  
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

