name: Helm Pull Request Build

on:
  pull_request:
    branches:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Set up Helm
      env:
        HELM_VERSION: "v3.16.1"
      run: |
        wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
        tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
        chmod +x /tmp/helm

    - name: Build Helm
      run: |
        source ./helm/build.sh
